language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "stable"
  - "11"
  - "10"
  - "9"
  - "8"
before_script:
  - export CI=true
services:
  - mongodb
install:
  - npm install
  - cd ./frontend && npm install
  - cd ../
script:
  - npm test
  - cd ./frontend && npm test
