language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "stable"
  - "11"
  - "10"
before_script:
  - export CI=true
services:
  - mongodb
install:
  - yarn install
  - cd ./frontend && yarn install
  - cd ../
script:
  - yarn test
  - cd ./frontend && yarn test
